TimeTracker-master/TimeTTTracker/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TimeTTTracker.Models;

namespace TimeTTTracker.Controllers
{
    public class ProjectController : Controller
    {
        ApplicationDbContext _context;

        public ProjectController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        public ActionResult Index()
        {
            var projekty = _context.Projects.ToList();
            return View(projekty);
            //return View();
        }
    }
}

TimeTracker-master/TimeTTTracker/Controllers/WorkerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TimeTTTracker.Models;

namespace TimeTTTracker.Controllers
{
    public class WorkerController : Controller
    {
        ApplicationDbContext _context;

        public WorkerController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        public ActionResult Index()
        {
            var pracownicy = _context.Workers.ToList();
            return View(pracownicy);
        }

        //[Authorize(Roles = "CanRegister")]
        //public ActionResult Register(Worker worker)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        var newWorker = new Worker
        //        {
        //            Imie = worker.Imie,
        //            Nazwisko = worker.Nazwisko,
        //            Email = worker.Email,
        //            Password = "zaw2ZAW@",
        //            Uprawnienia = worker.Uprawnienia
        //        };

        //        _context.Workers.Add(newWorker);
        //    }
        //    return View();
        //}

        public ActionResult Login()
        {
            return View();
        }
    }
}

TimeTracker-master/TimeTTTracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title — moja aplikacja platformy ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @{
        Html.RenderPartial("_NavBar");
    }
    <div class="container body-content">
        @RenderBody()

        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TimeTracker-master/TimeTTTracker/Views/Shared/_NavBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Nazwa aplikacji", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Projekty", "Index", "Project")</li>
                <li>@Html.ActionLink("Pracownicy", "Index", "Worker")</li>
                <li>@Html.ActionLink("Raport", "Contact", "Home")</li>
                <!-- OSTATNIE WPISY PRACOWNIKOW -->
                <!-- PROJEKTY KTORE ZOSTALY ZAKONCZONE W DANYM DNIU LUB SA W TRAKCIE -->
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>